services:
  server:
    image: isaa-ctaylor/stash
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - stash-data:/app/data
    ports:
      - "8080:8000"
    develop:
      watch:
        - action: sync+restart
          path: ./stash
          target: /app
          ignore:
            - ./stash/static/assets
            - ./stash/templates
        - action: sync
          path: ./stash
          target: /app

volumes:
  stash-data:
